# Generated by Django 5.1.5 on 2025-02-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
